services:
  neo4j:  # 'services'보다 2칸 들여쓰기
    image: neo4j:5.15.0
    container_name: neo4j-graph-rag  #
    ports:
      - "7474:7474"  # 외부(호스트):내부(컨테이너)
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/12341234
      - NEO4J_PLUGINS=["apoc"]