
spring:
  application:
    name: super-daddy
  config:
    import: "optional:file:.env[.properties]"
  ai:
    google:
      genai:
        project-id: ${GOOGLE_PROJECT_ID}
        api-key: ${GOOGLE_API_KEY}
        location: us-central1
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
        embedding:
          text:
            options:
              model: text-embedding-004
          project-id: ${GOOGLE_PROJECT_ID}
          api-key: ${GOOGLE_API_KEY}
          location: us-central1
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT}
        collection-name: parenting_guide
        initialize-schema: true



logging:
  level:
    org.springframework.ai: INFO
server:
  port: 35000
