spring:
  application:
    name: super-daddy
  config:
    import: "optional:file:.env[.properties]"
  ai:
    gemini:
      api-key: ${GOOGLE_API_KEY}
      chat:
        options:
          model: gemini-3-flash-preview
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-004
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: ${QDRANT_PORT}
        collection-name: parenting_guild
        initialize-schema: true

logging:
  level:
    org.springframework.ai: INFO
