
spring:
  application:
    name: super-daddy
  config:
    import: "optional:file:.env[.properties]"
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12341234


langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GOOGLE_API_KEY}
      model-name: gemini-2.5-flash
    embedding-model:
      api-key: ${GOOGLE_API_KEY}
      model-name: text-embedding-004

logging:
  level:
    root: INFO
server:
  port: 35000
